// Castor by IT Leonard
// ui/src/help/cards/profile.ts — Profile page & two-factor authentication help card.
import type { HelpCard } from "../types";

export const profileCard: HelpCard = {
  id: "profile",
  title: { en: "Your profile & 2FA", fr: "Votre profil & 2FA" },

  en: {
    summary: "Manage your account: change your password, enable TOTP two-factor authentication, keep your one-time recovery codes safe, and create API tokens to automate Castor.",
    sections: [
      {
        title: "What the Profile page is for",
        blocks: [
          { kind: "p", text: "The **Profile** page is where you manage your own account. From here you can change your **password**, turn **two-factor authentication (2FA)** on or off, and create **API tokens** for automation. It also shows your current **assurance level** — whether you signed in with a password only (`pwd`) or with a password plus a one-time code (`pwd+totp`)." },
          { kind: "note", text: "You reach this page from the **user menu** in the top bar (your avatar, on the right). The same menu also holds the **Theme** switch — each click cycles **Light → Dark → System** (System follows your OS preference)." },
          { kind: "callout", tone: "warn", text: "Enabling 2FA is **strongly recommended**, especially if your Castor instance is reachable from the Internet. Castor drives the Docker socket, which is effectively **root-equivalent** on the host — a stolen password alone should never be enough to take it over." },
        ],
      },
      {
        title: "Change your password",
        blocks: [
          { kind: "p", text: "Enter your current password and a new one. Castor requires a **minimum of 10 characters** for the new password. A longer passphrase is better than a short, complex one." },
        ],
      },
      {
        title: "Enable 2FA (TOTP)",
        blocks: [
          { kind: "p", text: "2FA adds a second factor: a **6-digit code** that changes every 30 seconds, generated by an authenticator app on your phone. To turn it on:" },
          { kind: "list", items: [
            "Click **Enable 2FA** — Castor displays a **QR code**.",
            "Scan the QR code with an authenticator app (**Google Authenticator**, **Microsoft Authenticator**, **Authy**, **1Password**…).",
            "Type the current **6-digit code** shown by the app to confirm the pairing.",
          ] },
          { kind: "note", text: "Can't scan the QR code? Most apps also accept the setup secret typed in manually." },
        ],
      },
      {
        title: "Recovery codes — save them now",
        blocks: [
          { kind: "p", text: "Once you confirm, Castor generates **10 single-use recovery codes**. Each one lets you sign in when you **don't have your phone** — for example if it is lost, stolen or wiped. They are your only way back into the account without the authenticator." },
          { kind: "callout", tone: "warn", text: "The recovery codes are shown **only once**, right after you enable 2FA. Download them and store them somewhere safe (a password manager, a printed sheet in a drawer). If you lose them **and** lose your phone, you are locked out." },
          { kind: "p", text: "Each code works a single time. Once you've used one to sign in, cross it off — it won't work again." },
        ],
      },
      {
        title: "Signing in & disabling 2FA",
        blocks: [
          { kind: "p", text: "With 2FA on, every sign-in asks for the 6-digit code after your password. Your assurance level then reads `pwd+totp`, which some actions require: Castor can enforce **2FA for mutations** (the \"require 2FA for mutations\" setting), and always requires a fresh code before opening an **exec terminal** into a container (a step-up to the higher AAL)." },
          { kind: "p", text: "To **disable** 2FA, Castor asks for your **password** to confirm it's really you. Disabling also invalidates your recovery codes; if you re-enable 2FA later, you'll get a fresh set of 10." },
        ],
      },
      {
        title: "API tokens (Personal Access Tokens)",
        blocks: [
          { kind: "p", text: "The **API tokens** card lets you create **Personal Access Tokens** to automate Castor without a browser session: shell scripts, **CI/CD pipelines**, or a **Prometheus** instance scraping the `/metrics` endpoint." },
          { kind: "p", text: "Click **New token**, give it a **name** you'll recognize later (e.g. “CI deploy”) and pick an **expiration** (30, 90 or 365 days, or never — 90 days is the default). The token — `castor_pat_` followed by a long random string — is then displayed with a copy button." },
          { kind: "callout", tone: "warn", text: "The token is shown **only once**, right after creation. Copy it before closing the dialog — afterwards the list only shows its **prefix** and metadata (created, expires, last used). If you lose it, revoke it and create a new one." },
          { kind: "p", text: "To use it, send it in the `Authorization: Bearer` header of your API requests:" },
          { kind: "cmd", command: "curl -H \"Authorization: Bearer castor_pat_...\" https://your-castor.example.com/api/hosts" },
          { kind: "p", text: "A token acts **as you**: it inherits your role's permissions, no more, no less. For example, an **operator**'s token can create networks and volumes, prune unused resources or update containers — but deletions still require a token owned by an **admin**. Being machine-to-machine, a token also passes the **“2FA required for mutations”** step-up on its own. Two things it can **never** do, though: manage API tokens (creating or revoking tokens takes a real browser session) and open an **exec terminal** into a container." },
          { kind: "p", text: "Made a token you no longer trust? Click **Revoke** in the list — requests using it are rejected **immediately**, and this cannot be undone. Expired tokens are rejected automatically." },
          { kind: "list", items: [
            "Prefer a **short expiration** — a token that dies on its own limits the damage if it leaks.",
            "Create **one token per usage** (one for CI, one for Prometheus…) so you can revoke one without breaking the others.",
            "Treat a token like a **password**: don't commit it to git, inject it via your CI's secret store.",
            "If a token leaks (pasted in a log, committed by mistake…), **revoke it right away** and issue a new one.",
          ] },
        ],
      },
      {
        title: "Pitfalls & good practices",
        blocks: [
          { kind: "list", items: [
            "Enable 2FA on **every** admin/operator account, not just yours.",
            "Store recovery codes **separately** from your phone — codes on the same device you'd lose defeats the purpose.",
            "Keep your server's `CASTOR_SECRET_KEY` in a safe place. 2FA secrets are sealed with **AES-256-GCM** using that key; without it, the sealed secrets become **unreadable** and enrolled users can't complete 2FA.",
            "Losing both your phone and your recovery codes means an admin has to reset your account — plan for it before it happens.",
          ] },
        ],
      },
      {
        title: "Documentation",
        blocks: [
          { kind: "doc", href: "https://datatracker.ietf.org/doc/html/rfc6238", label: "RFC 6238 — TOTP: Time-Based One-Time Password Algorithm" },
        ],
      },
    ],
  },

  fr: {
    summary: "Gérez votre compte : changez votre mot de passe, activez la double authentification TOTP, conservez précieusement vos codes de récupération à usage unique et créez des tokens API pour automatiser Castor.",
    sections: [
      {
        title: "À quoi sert la page Profil",
        blocks: [
          { kind: "p", text: "La page **Profil** est l'endroit où vous gérez votre propre compte. Vous pouvez y changer votre **mot de passe**, activer ou désactiver la **double authentification (2FA)**, et créer des **tokens API** pour l'automatisation. Elle affiche aussi votre **niveau d'assurance** actuel — si vous vous êtes connecté avec un mot de passe seul (`pwd`) ou avec un mot de passe plus un code à usage unique (`pwd+totp`)." },
          { kind: "note", text: "Vous accédez à cette page depuis le **menu utilisateur** de la barre du haut (votre avatar, à droite). Ce même menu contient aussi le sélecteur de **thème** — chaque clic fait défiler **Light → Dark → System** (System suit la préférence de votre OS)." },
          { kind: "callout", tone: "warn", text: "Activer la 2FA est **fortement recommandé**, surtout si votre instance Castor est accessible depuis Internet. Castor pilote le socket Docker, ce qui équivaut à un accès **root** sur l'hôte — un mot de passe volé ne devrait jamais suffire à en prendre le contrôle." },
        ],
      },
      {
        title: "Changer votre mot de passe",
        blocks: [
          { kind: "p", text: "Saisissez votre mot de passe actuel puis le nouveau. Castor exige **au minimum 10 caractères** pour le nouveau mot de passe. Une phrase de passe longue vaut mieux qu'un mot court et compliqué." },
        ],
      },
      {
        title: "Activer la 2FA (TOTP)",
        blocks: [
          { kind: "p", text: "La 2FA ajoute un second facteur : un **code à 6 chiffres** qui change toutes les 30 secondes, généré par une application d'authentification sur votre téléphone. Pour l'activer :" },
          { kind: "list", items: [
            "Cliquez sur **Activer la 2FA** — Castor affiche un **QR code**.",
            "Scannez le QR code avec une appli d'authentification (**Google Authenticator**, **Microsoft Authenticator**, **Authy**, **1Password**…).",
            "Saisissez le **code à 6 chiffres** affiché par l'appli pour confirmer l'appairage.",
          ] },
          { kind: "note", text: "Impossible de scanner le QR code ? La plupart des applis acceptent aussi la clé de configuration saisie à la main." },
        ],
      },
      {
        title: "Codes de récupération — sauvegardez-les tout de suite",
        blocks: [
          { kind: "p", text: "Une fois la confirmation faite, Castor génère **10 codes de récupération à usage unique**. Chacun vous permet de vous connecter quand vous **n'avez pas votre téléphone** — par exemple s'il est perdu, volé ou réinitialisé. C'est votre seul moyen de retrouver l'accès au compte sans l'appli d'authentification." },
          { kind: "callout", tone: "warn", text: "Les codes de récupération ne sont affichés **qu'une seule fois**, juste après l'activation de la 2FA. Téléchargez-les et rangez-les en lieu sûr (un gestionnaire de mots de passe, une feuille imprimée dans un tiroir). Si vous les perdez **et** que vous perdez votre téléphone, vous êtes bloqué." },
          { kind: "p", text: "Chaque code ne fonctionne qu'une seule fois. Dès que vous en avez utilisé un pour vous connecter, rayez-le — il ne servira plus." },
        ],
      },
      {
        title: "Se connecter & désactiver la 2FA",
        blocks: [
          { kind: "p", text: "Avec la 2FA activée, chaque connexion demande le code à 6 chiffres après le mot de passe. Votre niveau d'assurance affiche alors `pwd+totp`, ce qu'exigent certaines actions : Castor peut imposer la **2FA pour les mutations** (réglage « 2FA requise pour les mutations »), et exige toujours un code frais avant d'ouvrir un **terminal exec** dans un conteneur (une élévation vers le niveau d'assurance supérieur / step-up AAL)." },
          { kind: "p", text: "Pour **désactiver** la 2FA, Castor demande votre **mot de passe** pour confirmer que c'est bien vous. La désactivation invalide aussi vos codes de récupération ; si vous réactivez la 2FA plus tard, vous en obtiendrez 10 nouveaux." },
        ],
      },
      {
        title: "Tokens API (Personal Access Tokens)",
        blocks: [
          { kind: "p", text: "La carte **API tokens** vous permet de créer des **Personal Access Tokens** pour automatiser Castor sans session navigateur : scripts shell, **pipelines CI/CD**, ou une instance **Prometheus** qui scrape l'endpoint `/metrics`." },
          { kind: "p", text: "Cliquez sur **New token**, donnez-lui un **nom** que vous reconnaîtrez plus tard (ex. « CI deploy ») et choisissez une **expiration** (30, 90 ou 365 jours, ou jamais — 90 jours par défaut). Le token — `castor_pat_` suivi d'une longue chaîne aléatoire — s'affiche alors avec un bouton de copie." },
          { kind: "callout", tone: "warn", text: "Le token n'est affiché **qu'une seule fois**, juste après sa création. Copiez-le avant de fermer la fenêtre — ensuite, la liste ne montre que son **préfixe** et ses métadonnées (création, expiration, dernière utilisation). Si vous le perdez, révoquez-le et créez-en un nouveau." },
          { kind: "p", text: "Pour l'utiliser, envoyez-le dans l'en-tête `Authorization: Bearer` de vos requêtes API :" },
          { kind: "cmd", command: "curl -H \"Authorization: Bearer castor_pat_...\" https://votre-castor.example.com/api/hosts" },
          { kind: "p", text: "Un token agit **en votre nom** : il hérite des permissions de votre rôle, ni plus, ni moins. Par exemple, le token d'un **operator** peut créer des réseaux et des volumes, purger les ressources inutilisées ou mettre à jour des conteneurs — mais les suppressions exigent toujours un token appartenant à un **admin**. Étant machine-à-machine, un token satisfait aussi de lui-même le step-up **« 2FA requise pour les mutations »**. Deux choses lui restent en revanche **interdites** : gérer les tokens API (créer ou révoquer un token exige une vraie session navigateur) et ouvrir un **terminal exec** dans un conteneur." },
          { kind: "p", text: "Un token en qui vous n'avez plus confiance ? Cliquez sur **Revoke** dans la liste — les requêtes qui l'utilisent sont rejetées **immédiatement**, et c'est irréversible. Les tokens expirés sont rejetés automatiquement." },
          { kind: "list", items: [
            "Préférez une **expiration courte** — un token qui meurt tout seul limite les dégâts en cas de fuite.",
            "Créez **un token par usage** (un pour la CI, un pour Prometheus…) pour pouvoir en révoquer un sans casser les autres.",
            "Traitez un token comme un **mot de passe** : ne le committez pas dans git, injectez-le via le coffre à secrets de votre CI.",
            "Si un token fuite (collé dans un log, committé par erreur…), **révoquez-le immédiatement** et émettez-en un nouveau.",
          ] },
        ],
      },
      {
        title: "Pièges & bonnes pratiques",
        blocks: [
          { kind: "list", items: [
            "Activez la 2FA sur **tous** les comptes admin/operator, pas seulement le vôtre.",
            "Rangez les codes de récupération **séparément** de votre téléphone — des codes sur l'appareil même que vous risquez de perdre n'ont aucun intérêt.",
            "Conservez la `CASTOR_SECRET_KEY` de votre serveur en lieu sûr. Les secrets 2FA sont scellés en **AES-256-GCM** avec cette clé ; sans elle, les secrets scellés deviennent **illisibles** et les utilisateurs enrôlés ne peuvent plus valider leur 2FA.",
            "Perdre à la fois votre téléphone et vos codes de récupération oblige un administrateur à réinitialiser votre compte — anticipez-le avant que ça n'arrive.",
          ] },
        ],
      },
      {
        title: "Documentation",
        blocks: [
          { kind: "doc", href: "https://datatracker.ietf.org/doc/html/rfc6238", label: "RFC 6238 — TOTP : algorithme de mot de passe à usage unique basé sur le temps" },
        ],
      },
    ],
  },
};
